name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for Redis to be ready
        run: |
          for i in {1..10}; do
            (echo -n > /dev/tcp/localhost/6379) >/dev/null 2>&1 && break
            echo "Waiting for Redis to be ready..."
            sleep 1
          done

      - name: Build with Gradle
        run: ./gradlew clean build
